-- Active: 1719481981593@@127.0.0.1@3306@REACT_COMPILER
-- Creating the database
CREATE DATABASE REACT_COMPILER;


-- Account table 
CREATE TABLE ACCOUNTS (
    id CHAR(15) NOT NULL UNIQUE,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    password_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logged_in_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);


-- Missing Password 

CREATE TABLE RESET_PASSWORD (
    reset_token CHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (reset_token)
);

